# Generated by Django 3.1.7 on 2021-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HypsometricImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images')),
            ],
            options={
                'verbose_name_plural': 'HypsometricImages',
            },
        ),
    ]
