# Generated by Django 3.1.7 on 2021-05-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_hypsometricimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDetailsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(null=True, upload_to='uploaded_images')),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'SurfaceDetailsImages',
            },
        ),
        migrations.CreateModel(
            name='SurfaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images')),
            ],
            options={
                'verbose_name_plural': 'SurfaceImages',
            },
        ),
        migrations.AddField(
            model_name='hypsometricimages',
            name='details_map',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.mapdetailsimages'),
        ),
    ]
